### PR TITLE
fix: fixed style issues in small displays

### PR DESCRIPTION
**Pull request by GiftShower**
fixed a lot of styling errors that can be found on small displays 
overflowing below width 796 is not resolved

### CODE REVIEW

**Comment by hmtheboy154** [comment]
@Jackeagle next time tag @SGNight in since he re-write the site too

**Comment by SGNight** [comment]
this one has some conflicting issues with current website, it's breaking background and buttons, so it can't be merged, we should put it on hold for the time being and it doesn't solve the overflowing issue on small displays, I think I'll need a complete rebase of current website.

**Comment by mohdamin91** [comment]
Hello and hai all , i want asking for Bliss Os X86 , how can set rotate to portrait 90deg for permanent after and before install Bliss Os x86.

**Comment by electrikjesus** [comment]
Yeah, this PR should be abandoned. We have had a couple contributors come forward with proposals for new website designs, and we are just waiting for those to progress forward. 
The majority of users that would be downloading this operating system, won't be doing so from a phone anyways. So the tiny bit of styling that is off for mobile is acceptable for right now in my opinion

**Comment by electrikjesus** [comment]
> Hello and hai all , i want asking for Bliss Os X86 , how can set rotate to portrait 90deg for permanent after and before install Bliss Os x86.

This is not how you report an issue. Please see the documentation site for the multiple methods of how to do this

**Pull request closed without merging**
